#Build stage 
FROM node:18-alphine AS Build

WORKDIR /usr/src/app

COPY packages*.json ./ 

RUN npm install 

COPY . .

RUN npm run build

#PROD STAGE

FROM node:18-alphine

WORKDIR /usr/src/app

ARG NODE_ENV=production
ENV NODE_ENV=${NODE_ENV}

COPY --from=build /usr/src/app/dist ./dist

COPY package*.json ./ 

RUN npm install

EXPOSE 8000

CMD ["node", "dist/main.js"]